### ISSUE TITLE
`get_coastlines(geocentric=False)` latitude lines

### ISSUE THREAD

**Issue by trexfeathers** [bjlittle/geovista#13]
Non-geocentric coastlines currently include several continuous latitude lines:

<img width="404" alt="image" src="https://user-images.githubusercontent.com/40734014/142904727-9596deb8-e14e-4b8f-b603-8a0ad1e17fda.png">

This functionality is not yet used in any other part of GeoVista so I suggest removing it from the `get_coastlines()` API until the latitude lines can be removed.

**Comment by bjlittle** [comment]
@trexfeathers I'll leave this issue open, but the `geocentric` option is a placeholder for when we add projection support.

To avoid interim confusion, see https://github.com/bjlittle/geovista/commit/66e2ca54c4fbef5df67d3d3f9c91685b964a94e1, when temporarily removes this, but we can easily join the dots again when it makes sense :+1:

**Comment by bjlittle** [comment]
@trexfeathers Welcome to `geovista` :beers: 

And thanks for our very first issue... I'm sure there will be more to come :wink:

**Comment by trexfeathers** [comment]
We know this is still relevant 🙂

**Comment by trexfeathers** [comment]
This block is still in the code:

https://github.com/bjlittle/geovista/blob/bb6790f1df462fc789fc1b366ee7966f36eb9bf8/src/geovista/geometry.py#L255-L259

So I assume the issue is still relevant.

**Comment by trexfeathers** [comment]
🎉

**Comment by bjlittle** [comment]
@all-contributors please add @trexfeathers for bug
