### ISSUE TITLE
Sphinx docs and example gallery?

### ISSUE THREAD

**Issue by banesullivan** [bjlittle/geovista#14]
## 📚 Documentation

Would you be interested in placing all of the examples into a sphinx gallery much like [PyVista’s gallery](https://docs.pyvista.org/examples/index.html)? If so, I have some time for random side stuff right now and might be able to set this up for you.

I’m stoked to see this package and want to help you show off what it can do with PyVista!

**Comment by banesullivan** [comment]
This is all looking so awesome!! I'm so glad to hear how much PyVista is helping in your work!

> I'm planning on adding Coordinate Reference System support to geovista and planar projections with texture mapping (as above)... when that's in place then I'd really be grateful for any spare cycles that you might have to bootstrap the docs et al.
>
>You up for a bit of that?... which I'm thinking might be closer to Christmas, or just after (due to deadlines and commitments on this side)

Oh wow, that sounds fantastic. I'll try to help where I can in regards to helping get the docs building with embedded PyVista plots and perhaps a Sphinx-Gallery like this: https://sphinx-gallery.github.io/dev/auto_pyvista_examples/index.html

Just let me know how/where/when to get started, and I can give these things a go

**Comment by tkoyama010** [comment]
This issue is still important.

**Comment by bjlittle** [comment]
Finally, we've got skin in the game!

See https://geovista.readthedocs.io/en/latest/generated/gallery/index.html#examples-gallery 🥳

**Comment by tkoyama010** [comment]
Awesome job!

**Comment by banesullivan** [comment]
These look SO AWESOME!!!!

**Comment by bjlittle** [comment]
@all-contributors please add @banesullivan for ideas
