### ISSUE TITLE
PyPI release is empty

### ISSUE THREAD

**Issue by zklaus** [bjlittle/geovista#144]
## 🐛 Bug Report

The PyPI release contains only `__init__.py` and `_version.py`. Additionally, the changed versioning scheme from `.dev` to `a0` seems not to work as intended since `.dev` is considered newer than `a0`. Perhaps a `0.2` release is possible?

**Comment by bjlittle** [comment]
Hey @zklaus,

Greay to hear from you :smile: 

I've not made a release of `geovista` yet, although the first minor version 0.1.0 is imminent.

I grabbed the `geovista` namespace on both PyPI and conda-forge, but both contain empty packages. So this isn't a bug, it's just me securing ownership of the package name before anyone else took it before me :wink: 

Apologies for the confusion.

I suggest that you watch the repo and you'll be alerted by GH when I tag a release.

In fact, I'll leave this issue open and ping you here when `geovista` is lands.

Is that okay for now?

**Comment by zklaus** [comment]
I'll definitely watch :) I did run into this because I was following the [stable version of the Iris docs](https://scitools-iris.readthedocs.io/en/stable/further_topics/ugrid/operations.html) on a question from a colleague and that not working after doing a successful `mamba install geovista`.

**Comment by bjlittle** [comment]
@zklaus 

`geovista` has been tagged and released, and is now available on [conda-forge](https://anaconda.org/conda-forge/geovista?version=0.1.1&channel=main) and [PyPI](https://pypi.org/project/geovista/0.1.1/) :smile: 

Try it out:
```bash
conda create -n geovista -c conda-forge geovista
conda activate geovista
geovista examples --run all --verbose
```

Enjoy!

I'm going to close this issue now :+1: 

I'm going to be focusing a lot of development effort now on `geovista`. So things are going to be a wee bit fluid, but I'm keen to work towards a stable core and mature its features and capability.

**Comment by bjlittle** [comment]
@all-contributors please add @zklaus for bug
