### ISSUE TITLE
Unpin vtk 9.2.2

### ISSUE THREAD

**Issue by bjlittle** [bjlittle/geovista#160]
## 📰 Custom Issue

Unpin this defensive hard pin once https://github.com/pyvista/pyvista/issues/3869 is resolved

**Comment by banesullivan** [comment]
I think this is safe to unpin as this upstream issue seems to only affect some users on specific machines

**Comment by bjlittle** [comment]
Thanks @banesullivan 

I'll try this on the Met Office estate to see if this is still a local issue here.
