### ISSUE TITLE
Remove hard dependency on PyVistaQt

### ISSUE THREAD

**Issue by banesullivan** [bjlittle/geovista#161]
PyVistaQt is currently a hard requirement of this package. It should be opt-in as it is an incredibly heavy dependency stack and most users (well me at least) want to use this in Jupyter and avoid Qt

**Comment by bjlittle** [comment]
Yup, I totally agree. 

I'm going to make it optional, and put the glue functionality in a `geovistaqt` package. This'll address this dependency issue for you.

Now that I've finally got the first release of `geovista` banked, I can start to iterate quite quickly with frequent, small releases.

I'll get to this ASAP for you @banesullivan. I'm already scheduling another patch release v0.1.3 for next week, so I can roll this change into that for you 👍

**Comment by bjlittle** [comment]
@all-contributors please add @banesullivan for bug
