### ISSUE TITLE
Can't install geovista in dev mode due to scm-versioning

### ISSUE THREAD

**Issue by jamesp** [bjlittle/geovista#18]
## 🐛 Bug Report
Pip install from current head:

```bash
$ pip install -e .
[...]
      return _bump_dev(version) or _bump_regex(version)
    File "/var/tmp/pip-build-env-65a6ky4h/overlay/lib/python3.10/site-packages/setuptools_scm/version.py", line 210, in _bump_dev
      raise ValueError(
  ValueError: choosing custom numbers for the `.devX` distance is not supported.
   The 0.1.dev1 can't be bumped
  Please drop the tag or create a new supported one
```

This seems to be due to the `v0.1.dev1` tag and this line:
https://github.com/pypa/setuptools_scm/blob/4da6a5ac0efa68a2c92270112551c86b7ace12f5/src/setuptools_scm/version.py#L209-L215

## How To Avoid
Locally, run:
```bash
$ tag -d v0.1.dev1
$ pip install -e .
```

**Comment by bjlittle** [comment]
@jamesp This'll disappear on the next legitimate release.

The initial release was simply to land grab the namespace on pypi :+1:

**Comment by bjlittle** [comment]
@jamesp `geovista` is now tagged and released, and also available on [conda-forge](https://anaconda.org/conda-forge/geovista?version=0.1.1&channel=main) and [PyPI](https://pypi.org/project/geovista/0.1.1/) :smile: 


Try it out:
```bash
conda create -n geovista -c conda-forge geovista
conda activate geovista
geovista examples --run all --verbose
```

Enjoy!

I'm going to close this issue now :+1: 

I'm going to be focusing a lot of development effort now on `geovista`. So things are going to be a wee bit fluid, but I'm keen to work towards a stable core and mature its features and capability.

**Comment by bjlittle** [comment]
@all-contributors please add @jamesp for bug
