### ISSUE TITLE
No module named 'geovista.pantry'

### ISSUE THREAD

**Issue by PBrockmann** [bjlittle/geovista#196]
I get a  `ModuleNotFoundError: No module named 'geovista.pantry'`

I have installed anaconda 2020.11 
and I get a  geovista  at 0.1.dev1 release
after a classic `conda install -c conda-forge geovista`

Did I miss something  ?

**Comment by bjlittle** [comment]
Hey @PBrockmann,

Good to hear from you! 😃

Nope that's definitely wrong. The latest release is 0.1.4, see the [releases](https://github.com/bjlittle/geovista/releases), which is available on anaconda conda-forge geovista channel, see https://anaconda.org/conda-forge/geovista/files

The 0.1.dev1 release was just a placeholder package with no content to reserve the `geovista` namespace.

What platform are you attempting to install on?

When you do `conda search -c conda-forge geovista` what do you get?

**Comment by bjlittle** [comment]
I get the following:
```bash
itwl@vld173:> conda search -c conda-forge geovista
Loading channels: done
# Name                       Version           Build  Channel             
geovista                       0.1a0    pyhd8ed1ab_0  conda-forge         
geovista                    0.1.dev1    pyhd8ed1ab_0  conda-forge         
geovista                       0.1.0    pyhd8ed1ab_0  conda-forge         
geovista                       0.1.1    pyhd8ed1ab_0  conda-forge         
geovista                       0.1.2    pyhd8ed1ab_0  conda-forge         
geovista                       0.1.3    pyhd8ed1ab_0  conda-forge         
geovista                       0.1.4    pyhd8ed1ab_0  conda-forge         
```

**Comment by PBrockmann** [comment]
Indeed 
`conda install -c conda-forge geovista=0.1.4`

and a
`conda install -c conda-forge appdirs`

has solved this issue. 
Thnks.

**Comment by bjlittle** [comment]
@all-contributors please add @PBrockmann for bug
