### ISSUE TITLE
offset or drawn order for add_coastlines

### ISSUE THREAD

**Issue by PBrockmann** [bjlittle/geovista#203]
I cannot see coastlines from the example code:

```
import geovista as gv
from geovista.pantry import lfric_sst
import geovista.theme

# Load the sample data.
sample = lfric_sst()

# Create the mesh from the sample data.
mesh = gv.Transform.from_unstructured(
    sample.lons,
    sample.lats,
    connectivity=sample.connectivity,
    data=sample.data,
)

# Plot the mesh on a Robinson projection using an ESRI spatial reference identifier.
plotter = gv.GeoPlotter(crs="ESRI:54030")
sargs = {"title": f"{sample.name} / {sample.units}"}
plotter.add_mesh(mesh, cmap="thermal", show_edges=True, scalar_bar_args=sargs)
plotter.add_coastlines(resolution="50m", color="white")
plotter.view_xy()
plotter.add_axes()
plotter.show()
```

**Comment by bjlittle** [comment]
You may be also interested in https://github.com/pyvista/pyvista-xarray.

It's being developed by @banesullivan who is one of the founding creators of `pyvista` and a `vtk` guru from [kitware](https://www.kitware.com/).

The intention is that `pyvista-xarray` will [leverage `geovista` under the hood](https://github.com/pyvista/pyvista-xarray#upstream-work).

**Comment by bjlittle** [comment]
@PBrockmann Don't know if you've noticed yet, but I've already used some data that you shared with me a while back, which I'm using as example data in the `geovista` pantry which you can see with:

```bash
geovista examples --run from_unstructured__hexahedron --verbose
```
and
```bash
geovista examles --run from_unstructured__hexahedron_poly --verbose
```

I'd love to be able to cite you properly, see [here](https://github.com/bjlittle/geovista-data/tree/main/data/pantry#readme). Are my citation details correct?

Also, if you have more exciting data that you'd prefer I used instead, then please let me know 👍

**Comment by bjlittle** [comment]
Thanks!

Did you have any data that you'd prefer that I used? I'm happy to replace the sample that I've got if it better showcases your model?

**Comment by PBrockmann** [comment]
For now it will be ok.
Thanks
