### ISSUE TITLE
Odd behaviour with longitude extents at or near 180 degrees

### ISSUE THREAD

**Issue by hdyson** [bjlittle/geovista#229]
## 🐛 Bug Report
I'm experimenting with geovista with a view to understanding the capabilities with splitting and recombining data.  I started with very coarse slicing up of global UGrid data, and got unexpected results with longitude ranges of 180 degrees, or just below 180 degress.

## How to Reproduce

This example is adapted from the iris docs: https://scitools-iris.readthedocs.io/en/latest/further_topics/ugrid/operations.html#region-extraction

```py
from geovista import Transform
from geovista.geodesic import BBox
from iris import load_cube
from iris.experimental.ugrid import Mesh, PARSE_UGRID_ON_LOAD

from iris.tests import get_data_path
file_path = get_data_path(
    [
        "NetCDF",
        "unstructured_grid",
        "lfric_ngvat_2D_72t_face_half_levels_main_conv_rain.nc",
    ]
)

with PARSE_UGRID_ON_LOAD.context():
    global_cube = load_cube(file_path, "conv_rain")
print(global_cube)

lons, lats = global_cube.mesh.node_coords
face_node = global_cube.mesh.face_node_connectivity
indices = face_node.indices_by_location()
global_polydata = Transform.from_unstructured(
    lons.points, lats.points, indices, start_index=face_node.start_index
)

# Unexpected behaviour - returns 0 cells
region = BBox(lons=[0, 180, 180, 0], lats=[-25, -25, 45, 45])
region_polydata = region.enclosed(global_polydata, preference="center")
print(f"180 degree longitude: {region_polydata.n_cells}")

# Very unexpected behaviour - returns 39 cells
region = BBox(lons=[0, 179.9, 179.9, 0], lats=[-25, -25, 45, 45])
region_polydata = region.enclosed(global_polydata, preference="center")
print(f"179.9 degree longitude: {region_polydata.n_cells}")
```

## Expected Behaviour

Either an `Error` if this isn't something sensible to be asking for, or:
```py
# Expected behaviour - returns 402 cells
region = BBox(lons=[0, 179, 179, 0], lats=[-25, -25, 45, 45])
region_polydata = region.enclosed(global_polydata, preference="center")
print(f"179 degree longitude: {region_polydata.n_cells}")
```
## Environment
* OS & Version:  RHEL7
* GeoVista Version:  0.1.4

**Comment by bjlittle** [comment]
Thanks @hdyson for taking the time to experiment and feedback, it's really helpful.

I'll investigate and let you know how I get on :+1:

**Comment by bjlittle** [comment]
@hdyson Before digging into this, my initial expectation of the root cause is that you've not created a bounding box, but a bounding band, so to speak.

Regardlessly, it's a corner case that I should handle seamlessly underthehood, so that `geovista` gives you the result that you expect.

**Comment by hdyson** [comment]
@bjlittle Yeah, I'm really not sure whether geovista should just throw an error in this case, and tell the user that they're asking for something odd.  I did discuss this in the surgery with a few other scitools people too.

**Comment by bjlittle** [comment]
@hdyson Let me give you some example visuals of what's happening, which will help to clarify what's going on.

Hang tight...

**Comment by bjlittle** [comment]
@hdyson Okay, so I think I can explain this.

There's a disconnect between what you _think_ is happening and what is _actually_ happening. That's the confusion here.

To help explain, I'll render a 3D `BBox`s along with the global cube-sphere mesh, and hopefully this will clarify matters.

Let's take `BBox(lons=[0, 179, 179, 0], lats=[-25, -25, 45, 45])`. This actually renders as this:

<details>
<summary> 🗒 Click to expand for code... </summary>

```python
region = BBox(lons=[0, 179, 179, 0], lats=[-25, -25, 45, 45], c=512)

plotter = geovista.GeoPlotter()
plotter.add_mesh(global_polydata, show_edges=True)
plotter.add_mesh(region.mesh, color="red")
plotter.add_coastlines()
plotter.add_axes()
plotter.show()
```

</details>

![image](https://user-images.githubusercontent.com/2051656/236336132-0ade49d0-4486-44df-83db-fe0a2e0c2ce6.png)

The important point here is that the lines of the bounding box are geodesic great circles **not** constant lines of latitude and longitude.

Also, `BBox(lons=[0, 180, 180, 0], lats=[-25, -25, 45, 45])` renders as:

<details>
<summary> 🗒 Click to expand for code ... </summary>

```python
region = BBox(lons=[0, 180, 180, 0], lats=[-25, -25, 45, 45], c=512)

plotter = geovista.GeoPlotter()
plotter.add_mesh(global_polydata, show_edges=True)
plotter.add_mesh(region.mesh, color="red")
plotter.add_coastlines()
plotter.add_axes()
plotter.show()
```

</details>

![image](https://user-images.githubusercontent.com/2051656/236337123-a605cbef-bac8-4aa4-91a7-9b4071856905.png)

If you think about this long enough, now knowing that the lines are great circles, then you'll realise that the behaviour that you're getting is correct.

I'm guessing that what you actually want is something more along the lines of this:

<details>
<summary> 🗒Click to expand code... </summary>

```python
import pyvista as pv
from geovista.geodesic import line

lonlats = to_xy0(global_polydata.cell_centers(), closed_interval=True)
global_polydata["lons"] = lonlats[:, 0]
global_polydata["lats"] = lonlats[:, 1]

band = global_polydata.threshold((-25, 45), scalars="lats")
box = band.threshold((0, 180), scalars="lons")

plotter = geovista.GeoPlotter()
plotter.add_mesh(box, show_edges=True)
plotter.add_points(box.cell_centers(), render_points_as_spheres=True, color="yellow")
plotter.add_mesh(pv.Plane(direction=(0, 1, 0), i_size=2, j_size=2))
plotter.add_mesh(line(range(0, 181), [45]*181), color="red", line_width=3)
plotter.add_mesh(line(range(0, 181), [-25]*181), color="green", line_width=3)
plotter.add_coastlines()
plotter.add_axes()
plotter.show()
```

</details>

![image](https://user-images.githubusercontent.com/2051656/236344147-2988f0ae-62b6-431f-ab79-233ff3a3acca.png)

Projected to Plate Carrée is perhaps a little clearer...

<details>
<summary> 🗒Click to expand code... </summary>

```python
lonlats = to_xy0(global_polydata.cell_centers(), closed_interval=True)
global_polydata["lons"] = lonlats[:, 0]
global_polydata["lats"] = lonlats[:, 1]

band = global_polydata.threshold((-25, 45), scalars="lats")
box = band.threshold((0, 180), scalars="lons")

plotter = geovista.GeoPlotter(crs="+proj=eqc")
plotter.add_mesh(box, show_edges=True)
plotter.add_points(box.cell_centers(), render_points_as_spheres=True, color="yellow")
plotter.view_xy()
plotter.add_axes()
plotter.show()
```

</details>

![image](https://user-images.githubusercontent.com/2051656/236344961-65131c05-710d-4933-8a1d-e28ce1adca6b.png)

**Comment by hdyson** [comment]
So if I'm understanding this correctly, the issue boils down to a bounding box where the first two points are at (0W, -25N) and (180W, -25N) is getting an edge that roughly follows a line of longitude (i.e. going North-South over the pole) rather than the edge I was naively expecting going rougly East.  I think that make sense, since it is the shorter distance...

So I think the geovista issue becomes "how do we stop other people making this mistake", because I doubt I'll be the last!  I'm not sure we can give a sensible error here (it looks, naively, to be a tricky thing to validate) - is it something that needs a careful example in the documentation perhaps?

And for my own understanding, I'll dive into trying to grasp why we don't see the same scenario for the case with bounding box nodes at 179 degree longitude.

**Comment by bjlittle** [comment]
> So I think the geovista issue becomes "how do we stop other people making this mistake", because I doubt I'll be the last! I'm not sure we can give a sensible error here (it looks, naively, to be a tricky thing to validate) - is it something that needs a careful example in the documentation perhaps?

Totally agreed. The lack of documentation here isn't helpful, but rest assured that will happen shortly. In the meantime, it's safe to assume that **any** functionality within the `geovista.geodesic` module is based around **great circles**. I have a [GH Documentation](https://github.com/users/bjlittle/projects/3/views/1) project, where I've already captured this on your behalf.

I have plans to provision richer geometric primitives (most likely within `geovista.geometry`) that allow finer control by working in a provided CRS of your choosing. This will include a `BBox` that has straight lines constructed within the provided native CRS. Ideally this is what you want, and as I suspect, as will most other users 👍 

Before doing that there are some generic geometric tooling that I want to construct which will underpin the `geovista.geometric.BBox` capability, but more generally will allow you to essentially cookie-cutter a mesh with any 3D polygon.

**Comment by hdyson** [comment]
Thanks @bjlittle  - I really appreciate the explanation, and it sounds like you already have plans in place.  I'm going to close this issue then, since I think it's a bit redundant.  If this is still useful for you, obviously feel free to re-open it.

**Comment by trexfeathers** [comment]
I was just looking back at #59 - `PolyData.threshold()` definitely seems the right pattern for latitude bounding. I'm guessing this is going to be part of:

>I have plans to provision richer geometric primitives

?
