### ISSUE TITLE
What I realised GeoVista could achieve when creating the tutorial

### ISSUE THREAD

**Issue by tkoyama010** [bjlittle/geovista#373]
## Motivation

This is the memo of what I realised GeoVista could achieve when creating the tutorial.
1. Wind of the earth. Arrow vectors with glyphs are used to represent wind movement.
https://scitools.org.uk/cartopy/docs/v0.15/matplotlib/advanced_plotting.html#vector-plotting
https://unidata.github.io/MetPy/latest/index.html
2. Quake magnitude of the earth. A glyph-based sphere is used to represent magnitude. The ground should be translucent to show under the ground.

## Additional Context

</details>

**Comment by tkoyama010** [comment]
I am now attending Holoviz Tutorial in SciPy2023 and I found a good example of the earthquake using earthquake data in [USGS](https://www.usgs.gov/programs/earthquake-hazards).
<img width="1280" alt="dashboard" src="https://github.com/bjlittle/geovista/assets/7513610/b71b3a38-f3e4-48c8-a911-7b5427d8d43a">

**Comment by dennissergeev** [comment]
+1 for the wind arrows!

**Comment by tkoyama010** [comment]
Memo: https://earth.nullschool.net/

**Comment by bjlittle** [comment]
> Memo: https://earth.nullschool.net/

Yeah, it's neat, right? I discovered it a while back also 👍

**Comment by tkoyama010** [comment]
@bjlittle You have  quick ears :laughing:
