### ISSUE TITLE
Core dumped when using plotter.show()

### ISSUE THREAD

**Issue by giubonino** [bjlittle/geovista#375]
## 📰 Custom Issue

Hello everyone,

I am able to load all the examples and produce the plots, but any time I tried to show them or save them my kernel died.
It happens running the script either on a jupyter notebook or with Python command. 
Do you have any suggestions?

Thank you

**Comment by giubonino** [comment]
I am trying to use geovista on my university's HPC system.

Thank you again

**Comment by bjlittle** [comment]
@giubonino Thanks for raising the issue :+1: 

Could you give me a little more context to see if I can recreate or diagnose the issue...

How did you install `geovista`? Using `conda` or `pip`?

Are there any tracebacks or error messages that you can share with me? I'm guessing from the issue title it's just a hard core dump with no diagnostics, right?

There may be some incompatibility with the host platform / operating-system.

Let's take `geovista` out of the equation for now and make sure the `pyvista` is at least operational. Could you please try running the following and let me know if it works:

```python
import pyvista as pv

pv.Cube().plot()
```

**Comment by giubonino** [comment]
@bjlittle thank you for your answer,

I installed geovista using mamba. I want to use it on a remote server, so that I followed these instructions (https://docs.pyvista.org/version/stable/getting-started/installation.html). 
I manage to install all the required packages, all of them using mamba. Now I am getting this error, same error if I run the code you suggested. 
Any idea?
![Screen Shot 2023-07-11 at 16 44 04](https://github.com/bjlittle/geovista/assets/58305314/7f710e3d-b276-44f8-a066-27169c5da6dc)


Thank you

**Comment by bjlittle** [comment]
Ahhh okay, thanks for that @giubonino.

Right, great, I *think* this is now making sense. This helps narrow the issue down, plus the fact that you mention above that you're attempting to use it on a remote server helps... so this might explain the issue that you're having.

See these [PyVista - Running on Remote Servers](https://docs.pyvista.org/version/stable/getting-started/installation.html#running-on-remote-servers) instructions, perhaps they might help. Let me know.

Ping @tkoyama010 @banesullivan - Have you guys seen this kind of issue before on `pyvista`? If so, do you know the correct `pyvista` setup to recommend to @giubonino to unblock them?

**Comment by bjlittle** [comment]
@giubonino Okay, thanks.

I've pinged a couple of the `pyvista` core developers, who've got way more experience with this particular kind of issue. We're all at SciPy 2023 atm, so see if I can pull on their expertise here to help you out :+1:

**Comment by bjlittle** [comment]
@giubonino I don't know your particular setup, but after a minor bit of digging around, these two articles seems highly relevant:

1. https://github.com/CDAT/cdat/issues/1134
1. https://unix.stackexchange.com/questions/12755/how-to-forward-x-over-ssh-to-run-graphics-applications-remotely

When you read through `1.` the nub of the issue there (which appears similar to yours) is related to ssh X port forwarding (see this [comment](https://github.com/CDAT/cdat/issues/1134#issuecomment-91239682)). Are you able to run the `glxgears`? (demo app for GLX)

**Comment by giubonino** [comment]
Good morning @bjlittle,

Well, if I run glxgears, using the setting suggested in [here](https://docs.pyvista.org/version/stable/getting-started/installation.html) (e.g. export DISPLAY=:99.0 etc), I got this error:
**"Error: couldn't get an RGB, Double-buffered visual"**

I upgraded Xquartz, installed mesa-libgl, but still. I don't really know.

**Comment by giubonino** [comment]
Here we are @tkoyama010!

Thanks
![Screen Shot 2023-07-12 at 11 01 10](https://github.com/bjlittle/geovista/assets/58305314/98bd7176-865d-4f8a-b733-9bc7c943b7da)

**Comment by giubonino** [comment]
I don't know if could be related but I have similar warming when plotting with matplotlib. 
![Screen Shot 2023-07-12 at 11 18 30](https://github.com/bjlittle/geovista/assets/58305314/243bce31-8474-40af-8ea1-9894d5f801e3)

But in this case I have the pop-up with the plot.

**Comment by tkoyama010** [comment]
It seems that [Get report of capabilities for the render window](https://vtk.org/doc/nightly/html/classvtkRenderWindow.html#ad863f715738a960699758fbd3422257a) in vtk raise an error.
Could  you run the following code and confirm that the image is displayed?
```python
import pyvista

pyvista.set_jupyter_backend('static')
pyvista.global_theme.notebook = True
pyvista.start_xvfb()

pv.Cube().plot()
```

**Comment by giubonino** [comment]
@tkoyama010 nope, 

![Screen Shot 2023-07-12 at 11 22 53](https://github.com/bjlittle/geovista/assets/58305314/7cd75c89-962d-4f45-b137-8463a543cf04)

**Comment by tkoyama010** [comment]
@giubonino
One solution is to build and install vtk for the environment. Is it possible to install an off-screen vtk by referring to this document?
https://docs.pyvista.org/version/dev/extras/building_vtk.html#building-vtk

**Comment by giubonino** [comment]
@tkoyama010 thank you,

I have no the rights to do that, but I'll try to ask to the ITs. 
Meanwhile, is there a way to disable the visualisation mode and just save the figures as in matplotlib using "matplotlib.use('Agg')" ? I don't need to visualise them, I need just to save them.

Thank you

**Comment by tkoyama010** [comment]
@giubonino 
In my mind, the vtk published on PyPI cannot handle the case without a GPU environment. If you want to handle it without a GPU, please consider building the OSMA package from the documentation mentioned earlier.
https://docs.pyvista.org/version/dev/extras/building_vtk.html#building-osmesa

**Comment by tkoyama010** [comment]
That's cool. Thanks :)

**Comment by bjlittle** [comment]
@giubonino Is there any further support that we can offer you here?

It's kinda difficult to know how to advise you best next. 

Please feel free to leave this issue open or close it.

Either way, it would be lovely to know whether you finally get yourself up and running 👍

**Comment by bjlittle** [comment]
@giubonino I'm going to close this issue.

If you want to re-open it for further discussion, then please don't hesitate to do that :+1: 

Many thanks!

**Comment by giubonino** [comment]
Thank you @bjlittle 

Update: I still have the problem, but it is more then likely linked to my HPC system.

**Comment by bjlittle** [comment]
@all-contributors please add @giubonino for userTesting
