### ISSUE TITLE
Preview documentation from pull requests

### ISSUE THREAD

**Issue by tkoyama010** [bjlittle/geovista#391]
## 📚 Documentation

Our project can be configured to build and host documentation for every new pull request. Previewing changes during review makes it easier to catch formatting and display issues before they go live. This feature will be very useful for maintaining documentation in the future.
![github-build-status-reporting](https://github.com/bjlittle/geovista/assets/7513610/535237dc-5df8-4bb7-8182-0af5b44740eb)
- [Preview documentation from pull requests](https://docs.readthedocs.io/en/stable/pull-requests.html)
- [How to configure pull request builds](https://docs.readthedocs.io/en/stable/guides/pull-requests.html)

**Comment by bjlittle** [comment]
@tkoyama010 Thanks! Now that SciPy is over and the code base is relatively stablish, I'm keen to start banking the core documentation.

I've figured out the structure of the docs that I'd like to follow, so in the coming weeks I'm going to start to lay down the foundations of the docs.

This is super useful, thanks 😀👍

**Comment by tkoyama010** [comment]
@bjlittle 
Great, I have a few things I'd like to try about creating API documentation, so please mention me when it is ready.

**Comment by bjlittle** [comment]
@tkoyama010 I've enabled this now, see https://github.com/bjlittle/geovista/pull/550 as the first PR to auto-build the docs as part of CI 👍

**Comment by tkoyama010** [comment]
@bjlittle Awesome! Thanks for your work.
