### ISSUE TITLE
Update scalars on existing mesh

### ISSUE THREAD

**Issue by jbusecke** [bjlittle/geovista#449]
## 📰 Custom Issue

I recently produced [this](video) and am wondering if I could improve performance with these sorts of high resolution climate outputs.
The movie shows two 'animated' features:
a)  evolving scalars (time dependent velocity and salinity fields) with time
b)  A camera move

I wrote the model out in a fashing like this (pseudocode):
```python
import geovista as gv

ds = load_xarray_dataset
frames = range(n)
camera_path = define_camera_path(frames)

p = gv.GeoPlotter()
p.open_movie(f'something.mp4')

for frame in frames:
    # select timestep
    da = ds.sel(time=frame).YOUR_VARIABLE
    
   # create new mesh for each timestep (point a)
    mesh = gv.Transform.from_2d(da.lon, da.lat, data=da.data)
    mesh = mesh.threshold()
    actor = p.add_mesh(mesh)
    
   # Animate camera position (point b)
    p.camera_position = camera_path.points[frame,:]

    # write movie frame and remove actor
    p.write_frame()
    p.remove_actor(actor)

p.close()
```

This seems super inefficent to me. I actually do not need to redraw the mesh, but instead the whole point a) is currently a change in the scalar values. I saw that there is a possibility to [update just the scalars](https://docs.pyvista.org/version/stable/api/plotting/_autosummary/pyvista.Plotter.update_scalars.html) in pyvista. I wonder if there is an internal/external function that would allow me to 'map' my n dimensional array of scalar data with geovista to be in the proper format to use `pyvista.Plotter.update_scalars()` instead of removing/rebuilding the mesh.

**Comment by bjlittle** [comment]
Hey @jbusecke!

Great to hear from you.

Okay, I can see what you're doing, and your intuition is right ...

Given your example above, you should be able to do "something" like this:
```python
import geovista as gv

ds = load_xarray_dataset
frames = range(n)
camera_path = define_camera_path(frames)

p = gv.GeoPlotter()
p.open_movie(f'something.mp4')

# create the mesh with no data payload
mesh = gv.Transform.from_2d(da.lon, da.lat)

# this is the name of the active scalar that contains your frame data
# which can be anything, let's go with ...
name = "data-frame"

for frame in frames:
    # select timestep
    da = ds.sel(time=frame).YOUR_VARIABLE
    
    # set the active scalar with the data payload for the frame
    mesh[name] = da.data

    # threshold the mesh - this can change the mesh each frame,
    # so create a "frame" mesh
    frame = mesh.threshold()

    # this will add the named mesh to the plotter or replace it
    actor = p.add_mesh(frame, name=name)
    
    # Animate camera position (point b)
    p.camera_position = camera_path.points[frame, :]

    # write movie frame and remove actor
    p.write_frame()

p.close()
```

The above assumes that the relationship between the data and the original `mesh` geometry doesn't change.

Give it a whirl and let me know if that works. It's difficult to give solid advice without the data to play with, so I may hunt around for some at this end to confirm a working pattern.

Also, you may have already seen this, but this may be of [help](https://docs.pyvista.org/version/stable/examples/02-plot/movie.html).

🍻

**Comment by bjlittle** [comment]
@all-contributors please add @jbusecke for promotion

**Comment by bjlittle** [comment]
@jbusecke I'm going to close this issue, but if you have any further questions then please don't hesitate to ask in another issue ... or feel free to reopen this issue :+1:

Thanks :beers:

**Comment by bjlittle** [comment]
Reference https://vimeo.com/863996198

**Comment by jbusecke** [comment]
Thanks @bjlittle. I have not had a lot of time for pushing viz work recently but I am at a meetibg today and the rotating earth continues to impress people. I will definitely return to this soon.

**Comment by bjlittle** [comment]
@jbusecke Cool. I'll be here if you need me 👍

Are you at SciPy 2024 BTW?

I'm here in Tacoma if you wanted to hangout and catch-up

**Comment by jbusecke** [comment]
Unfortunately not, super bummed to miss it this year but maybe this sort of thing would be a good target to rally some pangeo folks either for next year or some other occasion?

**Comment by jbusecke** [comment]
Oh I absolutely do not mind. Love when my work is shared (and even more when it drops jaws 😂). I honestly think this sort of stuff is only scratching the surface of what would be possible using high resolution earth system model output 🤗. Very keen to advance this in the future!
