### ISSUE TITLE
Lock-file update PR's don't trigger PR checks

### ISSUE THREAD

**Issue by trexfeathers** [bjlittle/geovista#49]
## 🐛 Bug Report

[The lock-file update GitHub Action](https://github.com/bjlittle/geovista/blob/f11a7a54ef11d8542be632c29f9fe6653572879e/.github/workflows/ci-locks.yml) uses [peter-evans/create-pull-request](https://github.com/peter-evans/create-pull-request), which suffers from the known GHA restriction that prevents GHA's generating further GHA's - [documented here](https://github.com/peter-evans/create-pull-request/blob/18f7dc018cc2cd597073088f7c7591b9d1c02672/docs/concepts-guidelines.md#triggering-further-workflow-runs). This means that the main PR checks do not get run on pull requests proposing dependency updates.

The PR checks are an important benefit of the dependency lock-file PR concept, so we should either:
* Explore Peter Evans' various documented solutions.
* Seek an alternative GHA for raising PR's that doesn't have this limitation.

**Comment by bjlittle** [comment]
This is now resolved by using a GH App generated token.
