### ISSUE TITLE
Allow an additional dimension for data in geovista.Transform.from_1d etc.

### ISSUE THREAD

**Issue by stuartfox** [bjlittle/geovista#554]
## ✨ Feature Request

At present, the data array passed to geovista.Transform.from_1d is required to either be an array with (M, N) points, or MxN points. This proposal is to permit an extra dimension, so the data can also have shape (M, N, P) or (MxN, P).
## Motivation
One motivation for this change is to allow meshes to be created that represent RGB image values rather than scalar data. Use cases include, for example, plotting of limited-area satellite imagery on the globe.

For example, an RGB image of shape ```data(nx, ny, 3)``` and co-ordinate arrays ```x(nx)``` and ```y(ny)``` could be transformed to a mesh with
```
mesh = gv.Transform.from_1d(x, y, data)
```
creating ```mesh["point_data"]``` with shape (npoint, 3)
It could then be added as an RGB image to a plot with
```
plotter.add_mesh(mesh, rgb=True)
```

## Additional Context

<details>
<summary>Click to expand <b>this section...</b></summary>

```shell
Please provide additional verbose information here e.g., references, screenshots, listings etc
```
</details>

**Comment by bjlittle** [comment]
@stuartfox Thanks for taking the time to raise this feature request 🍻 

I think this would make a lovely extension to the `geovista.bridge`.

This would also apply to `RGBA` data as well, and would not only apply to `geovista.Transform.from_1d`, but also:
* `geovista.Transform.from_2d`,
* `geovista.Transform.from_unstructured`, and
* `geovista.Transform.from_points`

I've added this to the [GeoVista 0.5.0](https://github.com/users/bjlittle/projects/8) project, to ensure that we include this in the next release 👍

**Comment by trexfeathers** [comment]
I realised (later than I should) that this is useful for loads of things not just RGB. E.g. this is one of the ways to achieve animation by attaching a data array for each frame, and similarly if implementing a slider?

**Comment by bjlittle** [comment]
Completely, as with any other mesh rendered in a plotter scene.

**Comment by bjlittle** [comment]
@all-contributors please add @stuartfox for ideas
