### ISSUE TITLE
Move PyVista's GeoVista tutorial to GeoVista tutorial

### ISSUE THREAD

**Issue by tkoyama010** [bjlittle/geovista#635]
## 📚 Documentation

![image](https://github.com/bjlittle/geovista/assets/7513610/b2c96e78-6951-4fb8-bff7-c7d491de05d6)
I found that a GeoVista tutorial is in the works, and we had a GeoVista tutorial in the PyVista tutorial in SciPy2023, which can be found below. Moving it to the GeoVista tutorial and linking it from the PyVista tutorial would improve maintenance.
https://tutorial.pyvista.org/tutorial/05_action/a_lesson_geovista.html#sphx-glr-tutorial-05-action-a-lesson-geovista-py

**Comment by bjlittle** [comment]
@tkoyama010 Great idea! 

This makes a lot of sense from a maintenance perspective. We can ensure that the tutorial doesn't break and update it with new content when appropriate.

I've added this issue to the backlog of the forthcoming `0.5.0` release.

Thanks!

**Comment by bjlittle** [comment]
@tkoyama010 #983 Populated `geovista` with it's first tutorial :tada: 

I've based it on the material we put together last year for SciPy 2023.

Are you happy to close this issue now and we can deal with adding a link from the `pyvista-tutorial` via https://github.com/pyvista/pyvista-tutorial/pull/278

**Comment by bjlittle** [comment]
@tkoyama010 Now that https://github.com/pyvista/pyvista-tutorial/pull/278 is merged, I'm going to close this issue.

Thanks :+1:

**Comment by tkoyama010** [comment]
@all-contributors please add @bjlittle for tutorial
