### ISSUE TITLE
About README error

### ISSUE THREAD

**Issue by ChristmasZCY** [bjlittle/geovista#782]
## 📚 Documentation

There is 
```python
from geovista.pantry.data import ww3_global_tri 
```
 in the README file, 
but it can not take effect. 
It should be 
``` python 
from geovista.pantry import ww3_global_tri
```

**Comment by bjlittle** [comment]
Hey @ChristmasZCY!

Thanks for taking the time to raise this issue. Very much appreciated 😃 

We're in a bit of a weird position, in that there will be a breaking change introduced in the next release `0.5.0`, as we reorganised some of the modules within `geovista`.

The examples in the `README.md` are currently in agreement with the `main` branch, but not the latest available release `0.4.1`, which is a little bit confusing. Apologies.

What I'm going to do is revert the `README.md` so the examples quoted there are in alignment with `0.4.x`, as most users will be installing the latest release of `geovista` from `conda-forge` or `PyPI`.

I'll also create a draft pull-request to be merged prior to the forthcoming `0.5.0` release to revert the `README.md` to synchronise the examples with the codebase again.

Thanks for pointing this out 👍 

Also, checkout the other examples in the [GeoVista Gallery](https://geovista.readthedocs.io/en/latest/generated/gallery/index.html) ... note that, these examples are based on the `main` branch.

**Comment by ChristmasZCY** [comment]
Thank you, I'll follow it continuously!

**Comment by bjlittle** [comment]
@all-contributors please add @ChristmasZCY for bug
