### ISSUE TITLE
Unpin pydata-sphinx-theme

### ISSUE THREAD

**Issue by bjlittle** [bjlittle/geovista#815]
## 📰 Custom Issue

The `Toggle primary sidebar` for the [sphinx-book-theme](https://github.com/executablebooks/sphinx-book-theme) (`1.1.2`) no longer works with the latest available version `0.15.3` of [pydata-sphinx-theme](https://github.com/pydata/pydata-sphinx-theme/releases/tag/v0.15.3).

Remove the `pydata-sphinx-theme<0.15.3` temporary pin when this is no longer an issue.

Reference:
* Issue https://github.com/executablebooks/sphinx-book-theme/issues/836
* Pull-request #814

![image](https://github.com/bjlittle/geovista/assets/2051656/1ddbdb23-8d27-493f-9a3b-58208cb53909)

**Comment by tkoyama010** [comment]
Is there a clear reason to use the `sphinx-book-theme` instead of the `sphinx-pydata-theme`?

**Comment by bjlittle** [comment]
@tkoyama010 The `sphinx-book-theme` is built on top of the `sphinx-pydata-theme` and offers quite a lot of extra functionality, and allows you to incorporate notebooks more naturally.

The `Toggle primary sidebar` is particularly neat, as it allows the user to widen the display, which is handy when viewing interactive plots and they want more real-estate.

**Comment by bjlittle** [comment]
i.e., this ...

![image](https://github.com/bjlittle/geovista/assets/2051656/a1c4ed90-f1ba-4ad4-a9d9-24fe2c4ce933)

instead of this ...

![image](https://github.com/bjlittle/geovista/assets/2051656/71ec024c-4da6-418c-8509-10131c77e488)
