### ISSUE TITLE
Examples improvement: subject-based tags

### ISSUE THREAD

**Issue by trexfeathers** [bjlittle/geovista#823]
## 📚 Documentation

I love the use of tags in the documentation, and find myself using them more and more. I think we should include subject-based tags (e.g. `weather` / `oceans` / `geology`) as well:

- Show how flexible GeoVista is
- Specific reference to scientific fields (or even non-scientific ones!) may serve as a hook for people in those fields

Happy to have a go at this if I can make the time.

**Comment by bjlittle** [comment]
@trexfeathers That's a great idea 🚀 

Now that we have tags we can start to think of how users might get the most out of them.

Having domain/data specific tags seems like a natural way into `geovista` for the science community.

Looking forward to seeing how you want to do this ... go for it! 🤩
