### ISSUE TITLE
Examples improvement: H3 Spatial index

### ISSUE THREAD

**Issue by stephenworsley** [bjlittle/geovista#842]
## 📚 Documentation

I think this could do with a line or two at the start of the background to establish what H3, and I suppose more generally what a spatial index, is used for. Something like:

"A spatial index is a structured collection of shapes that allows you to approximately describe any region by simply taking a subset of shapes from that index. The H3 library, developed by Uber as an open source project, uses hexagons to divide up the earth into cells. H3 is hierarchical, meaning that there are multiple resolutions of hexagonal meshes dividing the earth. Depending on the resolution, these hexagonal cells range from ~1m^2 to ~4,000,000km^2."

**Comment by bjlittle** [comment]
@stephenworsley Awesome, go for it! 😉
