### ISSUE TITLE
Failing PyVista integration tests

### ISSUE THREAD

**Issue by akaszynski** [bjlittle/geovista#849]
PyVista integration tests are failing. See:
https://github.com/pyvista/pyvista/actions/runs/9628932678/job/26557721969?pr=6269

**Comment by tkoyama010** [comment]
Please also see https://github.com/pyvista/pyvista/pull/6292 .

**Comment by bjlittle** [comment]
@all-contributors please add @akaszynski for bug

**Comment by bjlittle** [comment]
Closed by https://github.com/pyvista/pyvista/pull/6381 and #998
