### ISSUE TITLE
Please add @bjlittle for talk in all-contributors

### ISSUE THREAD

**Issue by tkoyama010** [bjlittle/geovista#940]
## 📚 Documentation

1. I noticed that @bjlittle made a contribution for talk at [SciPy2023 LT](https://docs.google.com/presentation/d/1jHls1_7csJJ1cT47YWK1uiWJ9X8xUHGPoAMgxMhwdZI/edit?usp=sharing).
1. There is 📢talk contribution in https://allcontributors.org/docs/en/emoji-key#table .

**Comment by bjlittle** [comment]
@tkoyama010 Thanks!

Did you want to try using the bot to auto-generate a PR? 

It should "just work" for you. Also it would be a good test to see if that's the case.

Add a comment to this issue like `@all-contributors please add @bjlittle for talk`

**Comment by bjlittle** [comment]
Nuts ... of course the bot would scrape that comment. Doh!

@tkoyama010 You talked about `geovista` at the 2023 `pyvista` tutorial ... did you want to do the same for yourself please?

**Comment by bjlittle** [comment]
@tkoyama010 Could you also add yourself for `bug` and `question` please

**Comment by bjlittle** [comment]
Nice one! It works 🥳 

I think this makes it really easy for anyone to acknowledge other peoples contributions.

That's really great!

**Comment by bjlittle** [comment]
@all-contributors please add @banesullivan for promotion

**Comment by bjlittle** [comment]
@all-contributors please add @changliao1025 for ideas and promotion

**Comment by tkoyama010** [comment]
@allcontributors please add @edsaac for plugin
