### ISSUE TITLE
docs: verify osx key bindings

### ISSUE THREAD

**Issue by bjlittle** [bjlittle/geovista#963]
## 📰 Custom Issue

Require to verify the correctness of the [OSX keyboard and mouse bindings](https://geovista.readthedocs.io/en/latest/reference/bindings.html#key-bindings) documentation.

Particularly, I'm unsure about the correct bindings for `Rotate the rendered scene in 2-D (view plane)` and `Continuously zoom the rendering scene`.

![key-bindings-osx](https://github.com/bjlittle/geovista/assets/2051656/7644e0dc-88d6-4c9a-b23e-e7abd39d2646)

**Comment by bjlittle** [comment]
@ukmo-ccbunney Unfortunately, I don't have access to a Mac, but if I recall you do?

If you've got the time and inclination, I'd greatly appreciate if you can verify the bindings that I've documented :pray: 

If corrections are required, then please let me know either here in this issue, or push up a pull-request and I'll bank it in a heartbeat :wink:

**Comment by ukmo-ccbunney** [comment]
@bjlittle 
Most of the key bindings work for me (using a standard two button Logitech mouse - not an Apple Mouse), with the following exceptions (they work, but are different bindings to those specified):

 - Rotate the rendered scene: `Click`
 - Rotate the rendered scene in 2-D (view plane). `⌘ + Click` or `Ctrl + Click`
 - Continuously zoom the rendering scene: `Scroll wheel` or `R-Click`

I don't know for sure if the behaviour would be different with an Apple Mouse - I believe the "right click" on an Apple Mouse is achieved by Ctrl+Click.

However, the trackpad should have the same behaviour as the Apple Mouse and on my Mac `Ctrl+Click` rotates the view in  2D (same `⌘ + Click`), rather than binding to "continuous zooming".

**Comment by ukmo-ccbunney** [comment]
Also - I've just tested with Trame (3.6.2) and the only bindings that work are the `Ctrl+Click` (2d rotate), `Shift+Click` (panning) and the Mouse scroll zoom.

However, not all of them work in Trame on my Windows/Linux box either, only `r` (camera reset), `Ctrl+Click / R-Click / Scroll` (continuous zoom), `Middle-Click` (pan) work.

**Comment by bjlittle** [comment]
@ukmo-ccbunney Thanks, that's great! :100: 

Yeah, this just seems all a tad confusing, particularly when the rendering backend changes things and also the platform and also what kind of mouse you have ... jeez.

So after a bit a research it seems that `R-Click` is the same as `Ctrl-Click` on OSX (and even that's configurable) ... so to keep things sane-ish, would you agree with the following for OSX:

- Rotate the rendered scene in 3-D: `Click`
- Rotate the rendered scene in 2-D (view plane): `⌘ + Click` or `Ctrl + Click`
- Continuously zoom the rendering scene: `Mouse Wheel` or `R-Click`

I guess the OSX user can translate `R-Click` to be whatever they want it to be in this case :thinking:

**Comment by bjlittle** [comment]
@all-contributors please add @ukmo-ccbunney for ideas and userTesting

**Comment by ukmo-ccbunney** [comment]
> @ukmo-ccbunney Thanks, that's great! 💯
> 
> Yeah, this just seems all a tad confusing, particularly when the rendering backend changes things and also the platform and also what kind of mouse you have ... jeez.
> 
> So after a bit a research it seems that `R-Click` is the same as `Ctrl-Click` on OSX (and even that's configurable) ... so to keep things sane-ish, would you agree with the following for OSX:
> 
> * Rotate the rendered scene in 3-D: `Click`
> * Rotate the rendered scene in 2-D (view plane): `⌘ + Click` or `Ctrl + Click`
> * Continuously zoom the rendering scene: `Mouse Wheel` or `R-Click`
> 
> I guess the OSX user can translate `R-Click` to be whatever they want it to be in this case 🤔

Those certainly work in my case, although confusingly `Ctrl+Click` and `R-Click` aught to be the same thing in MacOS world, but are clearly mapping to different events here 🤷‍♀️. It would be nice to get someone with an Apple Mouse to confirm the behaviour there!

**Comment by bjlittle** [comment]
I'm heading to SciPy in Tacoma, WA in the next couple of days to hang with the PyVista devs, so I'll ask them for some clarity.

I did notice that PyVista confusingly document OSX with `Ctrl + Click` doing two different things, see [here](https://docs.pyvista.org/version/stable/api/plotting/plotting.html#plotting) i.e., `Rotate the rendering scene in 2-D` and `Continuously zoom the rendered scene` :confused:

**Comment by bjlittle** [comment]
I'll roll with your above suggested changes and take it from there.

Thanks so much for your help on this one mate :beers:
