### ISSUE TITLE
Offer NASA Black Marble Texture

### ISSUE THREAD

**Issue by bjlittle** [bjlittle/geovista#992]
## ✨ Feature Request

Complement the textures available "out-the-box" within `geovista` to include the [NASA Black Marble](https://earthobservatory.nasa.gov/images/90008/night-light-maps-open-up-new-applications).

https://github.com/bjlittle/geovista/assets/2051656/da319b8f-4950-4a1d-aaac-a7e9f2a976ad

**Comment by tkoyama010** [comment]
@all-contributors please add @Hedonical for idea
